server:
  port: 8082
course:
  environment: default
services:
  accounts:
    base-url: ${ACCOUNTS_BASE_URL:http://localhost:8081}
    timeout: ${ACCOUNTS_TIMEOUT:1s}
    total-timeout: ${ACCOUNTS_TOTAL_TIMEOUT:3s}
jwt:
  secret: ${JWT_SECRET:01234567890123456789012345678901}
management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      probes:
        enabled: true
